### ISSUE TITLE
Fails to parse large xml sitemap. May be due to time out or low memory

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#150]
Only the ~700 fist URL are read from the site map.

After running collector-http on a site map it manage to parse out the first ~700 URL before it fails. The number of URLs parsed varies from time to time. Eg. some time it parses 680 URLs, other time it's 710 or another number close to 700.

I extended the log message to also print the stack trace. I would guess that the XML stream is broken for some reason which in turn brakes the xml. It may be time out or low memory related. The server which I run this on only have 4 GB RAM.

The sitemap is valid.

The exception varies from time to time depending on where the XML is broken. The latest exception which I cough was:
```
uu-web-special: 2015-09-23 14:55:22 ERROR - Cannot fetch sitemap: http://an-url/sitemap.xml -- Likely an invalid sitemap XML format causing a parsing error (actual error: Unexpected EOF; was expecting a close tag for element <loc>
 at [row,col {unknown-source}]: [2656,2523]).
com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <loc>
 at [row,col {unknown-source}]: [2656,2523]
        at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:685)
        at com.ctc.wstx.sr.BasicStreamReader.throwUnexpectedEOF(BasicStreamReader.java:5519)
        at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2722)
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
        at com.norconex.collector.http.sitemap.impl.StandardSitemapResolver.parseLocation(StandardSitemapResolver.java:213)
        at com.norconex.collector.http.sitemap.impl.StandardSitemapResolver.resolveLocation(StandardSitemapResolver.java:147)
        at com.norconex.collector.http.sitemap.impl.StandardSitemapResolver.resolveSitemaps(StandardSitemapResolver.java:95)
        at com.norconex.collector.http.pipeline.queue.HttpQueuePipeline$SitemapStage.executeStage(HttpQueuePipeline.java:127)
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:31)
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:24)
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
        at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:168)
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:123)
        at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:113)
        at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:197)
        at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:172)
        at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
        at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:352)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:302)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:172)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:121)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:69)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:64)
```

**Comment by leonardsaers** [comment]
I also get another exception just before the one mentioned above.

```
uu-web-special: 2015-09-23 14:55:22 ERROR - [com.ctc.wstx.exc.WstxLazyException] Connection reset
[com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxIOException: Connection reset
        at com.ctc.wstx.exc.WstxLazyException.throwLazily(WstxLazyException.java:45)
        at com.ctc.wstx.sr.StreamScanner.throwLazyError(StreamScanner.java:728)
        at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3678)
        at com.ctc.wstx.sr.BasicStreamReader.getText(BasicStreamReader.java:860)
        at com.norconex.collector.http.sitemap.impl.StandardSitemapResolver.parseLocation(StandardSitemapResolver.java:193)
        at com.norconex.collector.http.sitemap.impl.StandardSitemapResolver.resolveLocation(StandardSitemapResolver.java:147)
        at com.norconex.collector.http.sitemap.impl.StandardSitemapResolver.resolveSitemaps(StandardSitemapResolver.java:95)
        at com.norconex.collector.http.pipeline.queue.HttpQueuePipeline$SitemapStage.executeStage(HttpQueuePipeline.java:127)
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:31)
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:24)
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
        at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:168)
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:123)
        at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:113)
        at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:197)
        at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:172)
        at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
        at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:352)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:302)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:172)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:121)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:69)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:64)
Caused by: com.ctc.wstx.exc.WstxIOException: Connection reset
        at com.ctc.wstx.sr.StreamScanner.constructFromIOE(StreamScanner.java:633)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1007)
        at com.ctc.wstx.sr.BasicStreamReader.readTextSecondary(BasicStreamReader.java:4647)
        at com.ctc.wstx.sr.BasicStreamReader.readCoalescedText(BasicStreamReader.java:4146)
        at com.ctc.wstx.sr.BasicStreamReader.finishToken(BasicStreamReader.java:3720)
        at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3676)
        ... 20 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:200)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:191)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at com.ctc.wstx.io.BaseReader.readBytes(BaseReader.java:155)
        at com.ctc.wstx.io.UTF8Reader.loadMore(UTF8Reader.java:368)
        at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:111)
        at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:86)
        at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:56)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1001)
        ... 24 more
```

**Comment by essiembre** [comment]
I will give it a try myself when I get a chance, but in the meantime, can the settings on [GenericHttpClientFactory](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html) help resolve this?  Like the ``connectionTimeout`` or ``socketTimeout`` settings. 

It does not look like a timeout but maybe it is related.

**Comment by leonardsaers** [comment]
Well, it work when specifying the time out parameter :)

I added the following configuration.
```xml
  <httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
      <cookiesDisabled>false</cookiesDisabled>
      <connectionTimeout>5000</connectionTimeout>
      <socketTimeout>5000</socketTimeout>
      <connectionRequestTimeout>5000</connectionRequestTimeout>
  </httpClientFactory>
```

The site map parsing problem returns when I remove the configuration. So it's most likely that the problem is related to some kind of time out.

This issue is now solved for me, but would it not be better if StandardSitemapResolver first downloaded the entire site map before parsing it? That would make it less likely that the site map stream ends by a time out.


Thanks for the help :)

**Comment by essiembre** [comment]
I followed your advice and the collector will now save sitemap files locally first before parsing them.  Get the new [snapshot release](https://www.norconex.com/collectors/collector-http/download). It would be nice if you could test it against your site again with your previous config that made it fail.

**Comment by leonardsaers** [comment]
Thanks, I will try this out.

**Comment by leonardsaers** [comment]
Using the latest SNAPSHOT, the crawler fails when parsing sitemap. I get the following log message.

```
web: 2015-10-12 14:04:57 ERROR - Cannot fetch sitemap: http://www.somepage.se/sitemap_index.xml (Timeout waiting for connection from pool)
web: 2015-10-12 14:05:27 ERROR - Cannot fetch sitemap: http://www.somepage.se/sitemap.xml (Timeout waiting for connection from pool)
```

I could look deeper into this. It may be some misconfiguration from my side.

The sitemap.xml exists and is valid. The sitemap_index.xml does not exist.

**Comment by essiembre** [comment]
This timeout is on the top-level sitemap file... so not the same issue you originally reported where timeouts were occurring when it was processing many sitemap (children) files at once, creating many connections at once.

Does it timeout on any page or just the sitemap one(s)?  What if you have ``<sitemap ignore="true">``, do you get timeouts on your regular pages?

**Comment by essiembre** [comment]
Is this still happening for you? Otherwise I suggest we close this issue.

**Comment by leonardsaers** [comment]
I get the "Cannot fetch sitemap" error using verion 2.2.1. So the error has not anything to do with this change.

I have tried downloading large sitemaps using the snapshots and it works.

**Comment by essiembre** [comment]
Thanks for the clarifications.  Since this works with the snapshot, I am closing.
