### ISSUE TITLE
Cannot persist status update for job

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#151]
I'm trying MongoDB instead of MapDB. I have in the config file:
```
  <crawlDataStoreFactory  
      class="com.norconex.collector.http.data.store.impl.mongo.MongoCrawlDataStoreFactory">
  </crawlDataStoreFactory>	  
```
I've run the collector once with MongoDB, with ```start``` and it has finished right. I've run it , again with ```start```, and I've gotten this fatal error, related to ```\progress\latest\status\``` status file. Any idea?.
```
[non-job]: 2015-09-24 13:27:18 INFO - Starting execution.
MongoDB (crawler): 2015-09-24 13:27:18 INFO - Running MongoDB (crawler): BEGIN (Thu Sep 24 13:27:18 CEST 2015)
MongoDB (crawler): 2015-09-24 13:27:18 INFO - MongoDB (crawler): RobotsTxt support: false
MongoDB (crawler): 2015-09-24 13:27:18 INFO - MongoDB (crawler): RobotsMeta support: true
MongoDB (crawler): 2015-09-24 13:27:18 INFO - MongoDB (crawler): Sitemap support: false
MongoDB (crawler): 2015-09-24 13:27:18 INFO - MongoDB (crawler): Canonical links support: true
MongoDB (crawler): 2015-09-24 13:27:18 INFO -           CRAWLER_STARTED
MongoDB (crawler): 2015-09-24 13:27:18 INFO - MongoDB (crawler): Crawling references...
MongoDB (crawler): 2015-09-24 13:27:19 INFO -          DOCUMENT_FETCHED: http://www.federacionpiraguismodeextremadura.com
MongoDB (crawler): 2015-09-24 13:27:19 INFO -       CREATED_ROBOTS_META: http://www.federacionpiraguismodeextremadura.com
MongoDB (crawler): 2015-09-24 13:27:19 INFO -            URLS_EXTRACTED: http://www.federacionpiraguismodeextremadura.com
MongoDB (crawler): 2015-09-24 13:27:19 INFO -          DOCUMENT_FETCHED: http://www.federacionpiraguismodeextremadura.com/flateral.php
MongoDB (crawler): 2015-09-24 13:27:19 INFO -       CREATED_ROBOTS_META: http://www.federacionpiraguismodeextremadura.com/flateral.php
MongoDB (crawler): 2015-09-24 13:27:19 INFO -            URLS_EXTRACTED: http://www.federacionpiraguismodeextremadura.com/flateral.php
MongoDB (crawler): 2015-09-24 13:27:19 INFO -          DOCUMENT_FETCHED: http://www.federacionpiraguismodeextremadura.com/central.php
MongoDB (crawler): 2015-09-24 13:27:19 INFO -       CREATED_ROBOTS_META: http://www.federacionpiraguismodeextremadura.com/central.php
MongoDB (crawler): 2015-09-24 13:27:19 INFO -            URLS_EXTRACTED: http://www.federacionpiraguismodeextremadura.com/central.php
MongoDB (crawler): 2015-09-24 13:27:20 INFO -         DOCUMENT_IMPORTED: http://www.federacionpiraguismodeextremadura.com
MongoDB (crawler): 2015-09-24 13:27:20 INFO -         DOCUMENT_IMPORTED: http://www.federacionpiraguismodeextremadura.com/flateral.php
MongoDB (crawler): 2015-09-24 13:27:20 INFO -       REJECTED_UNMODIFIED: http://www.federacionpiraguismodeextremadura.com/flateral.php
MongoDB (crawler): 2015-09-24 13:27:20 INFO -       REJECTED_UNMODIFIED: http://www.federacionpiraguismodeextremadura.com
MongoDB (crawler): 2015-09-24 13:27:20 FATAL - MongoDB (crawler): An error occured that could compromise the stability of the crawler. Stopping excution to avoid further issues...
com.norconex.jef4.JEFException: Cannot persist status update for job: MongoDB (crawler)
	at com.norconex.jef4.suite.JobSuite$2.statusUpdated(JobSuite.java:359)
	at com.norconex.jef4.status.JobStatusUpdater.setProgress(JobStatusUpdater.java:50)
	at com.norconex.collector.core.crawler.AbstractCrawler.setProgress(AbstractCrawler.java:430)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:377)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Cannot create status file: c:\CRAWLER\collectors\MongoDB\work\progress\latest\status\MongoDB_32__40_crawler_41___MongoDB_32__40_crawler_41_.job
	at com.norconex.jef4.status.FileJobStatusStore.write(FileJobStatusStore.java:125)
	at com.norconex.jef4.suite.JobSuite$2.statusUpdated(JobSuite.java:355)
	... 7 more
MongoDB (crawler): 2015-09-24 13:27:20 INFO - MongoDB (crawler): Stopping the crawler.
MongoDB (crawler): 2015-09-24 13:27:20 INFO -         DOCUMENT_IMPORTED: http://www.federacionpiraguismodeextremadura.com/central.php
MongoDB (crawler): 2015-09-24 13:27:20 INFO -       REJECTED_UNMODIFIED: http://www.federacionpiraguismodeextremadura.com/central.php
MongoDB (crawler): 2015-09-24 13:27:20 INFO -          DOCUMENT_FETCHED: http://www.federacionpiraguismodeextremadura.com/Bases/IVOlimpiadas2015.jpg
MongoDB (crawler): 2015-09-24 13:27:20 INFO -       CREATED_ROBOTS_META: http://www.federacionpiraguismodeextremadura.com/Bases/IVOlimpiadas2015.jpg
MongoDB (crawler): 2015-09-24 13:27:20 INFO -            URLS_EXTRACTED: http://www.federacionpiraguismodeextremadura.com/Bases/IVOlimpiadas2015.jpg
MongoDB (crawler): 2015-09-24 13:27:20 INFO -         DOCUMENT_IMPORTED: http://www.federacionpiraguismodeextremadura.com/Bases/IVOlimpiadas2015.jpg
MongoDB (crawler): 2015-09-24 13:27:20 INFO -    DOCUMENT_COMMITTED_ADD: http://www.federacionpiraguismodeextremadura.com/Bases/IVOlimpiadas2015.jpg
MongoDB (crawler): 2015-09-24 13:27:20 INFO - MongoDB (crawler): Crawler stopping: committing documents.
MongoDB (crawler): 2015-09-24 13:27:20 INFO - Committing 1 files
MongoDB (crawler): 2015-09-24 13:27:20 INFO - Sending 1 documents to Solr for update/deletion.
MongoDB (crawler): 2015-09-24 13:27:20 INFO - Done sending documents to Solr for update/deletion.
MongoDB (crawler): 2015-09-24 13:27:20 INFO - MongoDB (crawler): 4 reference(s) processed.
MongoDB (crawler): 2015-09-24 13:27:20 INFO - MongoDB (crawler): Crawler stopped.
MongoDB (crawler): 2015-09-24 13:27:20 INFO - MongoDB (crawler): Crawler executed in 2 seconds.
MongoDB (crawler): 2015-09-24 13:27:20 INFO - Running MongoDB (crawler): END (Thu Sep 24 13:27:18 CEST 2015)

```

**Comment by pascaldimassimo** [comment]
Hi @csaezl,

According to the stack trace, this error happens when the .job file is written to disk. If I look at the code of FileJobStatusStore (line 125), I see that it will send an IOException if the file already exists. At the moment, I don't think this is related specifically to the Mongo data store. Can you reproduce this issue every time you run the crawler? And can you check if you have this issue with another data store (like the default one)? 

@essiembre why do you think the .job file already exists? Should the code handle this possibility?

**Comment by csaezl** [comment]
Doing some investigation, having removed all the records from MongoDB_(crawler) data base and deleted previously the ```work``` folder where the ```progress\latest\status\MongoDB_32__40_crawler_41___MongoDB_32__40_crawler_41_.job``` file will be created:

a) I run the crawler with:
```
<url>http://www.federacionpiraguismodeextremadura.com</url>
```
I got the error mentioned in my previous post (even thought the file didn't exist previously) with the result:
reference(s) processed: 4
DOCUMENT_COMMITTED_ADD: 4
Documents in MongoDB: 35
From the .job file: ```note=4 references processed out of 35```

The difference I can see from the first run in my previous post (that processed 1812 references)  is that in the previous post the MongoDB_(crawler) data base didn't exist yet.

b) I run the crawler with:
```
<url>http://www.ideextremadura.es</url>
```
I got the result:
reference(s) processed: 39
DOCUMENT_COMMITTED_ADD: 37
REJECTED_REDIRECTED: 1
REJECTED_NOTFOUND: 1
Documents in MongoDB: 39

c) I run the crawler with:
```
<url>http://www.organicsextremadura.com</url>
```
I got the result:
reference(s) processed: 94
DOCUMENT_COMMITTED_ADD: 50
Read timed out: 37
REJECTED_CANONICAL: 7
Documents in MongoDB: 94

So it only seems to fail with the first URL.
Finally I have deleted the MongoDB_(crawler) data base and run the crawler with:

<url>http://www.federacionpiraguismodeextremadura.com</url>

but still get the status file error. Don't know what the problem is with this URL.

**Comment by essiembre** [comment]
I suspect it may be a concurrency issue when trying to write the file.  As a test, do you have the same problem if you run with only 1 thread?

**Comment by csaezl** [comment]
No, with 1 thread it doesn't produce any error. I've run the config file twice and both ended without error, The second one with REJECTED_UNMODIFIED.

**Comment by essiembre** [comment]
I believe to have fixed this issue in this new [snapshot release](https://www.norconex.com/collectors/collector-http/download). Please give it a try.

**Comment by csaezl** [comment]
I've run it twice (ADD/UNMODIFIED) and work fine

**Comment by csaezl** [comment]
With 3 threads

**Comment by essiembre** [comment]
Great! Thanks for testing.
