### ISSUE TITLE
filtering URLs

### ISSUE THREAD

**Issue by nuliknol** [Norconex/collector-http#233]
In order to filter crawling to a specific country level domain, I am following the instructions on the minimum test:
http://www.norconex.com/product/collector-http-test/minimum.php
which says I have to add this config:
```xml
  <referenceFilters>
    <filter class="com.norconex.collector.http.filter.impl.RegexURLFilter"     onMatch="include">http://www.YourOwnUrl.com/.*</filter>
  </referenceFilters>
```

but I get this error:
```
com.norconex.collector.core.CollectorException: Cannot load crawler configurations.
        at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:93)
        at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:183)
        at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:76)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: com.norconex.commons.lang.config.ConfigurationException: This class could not be instantiated: "com.norconex.collector.http.filter.impl.RegexURLFilter".
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:190)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:333)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:265)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:115)
        at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadReferenceFilters(AbstractCrawlerConfig.java:387)
        at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:314)
        at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:123)
        at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:83)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: com.norconex.collector.http.filter.impl.RegexURLFilter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:188)

```

which means, it can not find class name.  I have verified and the class name is written correctly. I just copied and pasted from the example, why it doesn't work?
This is the part of my configuration file, just in case:

```xml
<referenceFilters>
    <filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude">jpg,gif,png,ico,css,js,gz,bz</filter>
    <filter class="com.norconex.collector.http.filter.impl.RegexURLFilter" onMatch="include">http.*nz/</filter>
    <filter class="com.norconex.collector.http.filter.impl.RegexURLFilter" onMatch="include">http.*nz</filter>
</referenceFilters>
```
With this config I pretend to crawl only sites in New Zealand, but I am not sure if it will work yet, I didn't reach the testing part yet.

**Comment by essiembre** [comment]
It looks like the content of that test page has not been updated in a while!  For staying on a domain, there is now an easier option:
```xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
  <url>http://www.YourOwnUrl.com/</url>
</startURLs>
```

For samples, look at those shipped with the product, which are also available from that page: http://www.norconex.com/collectors/collector-http/configuration.  You will also find there all possible configuration options and they should all be up-to-date.

Let me know if the above suggestion works for you.

**Comment by essiembre** [comment]
I also updated the sample web pages to a working example: http://www.norconex.com/product/collector-http-test/minimum.php.  Thanks for reporting this.

**Comment by nuliknol** [comment]
Thanks! The stayOnDomain is simple and great option, but I have many pages I need to crawl on a specific country level domain.

**Comment by essiembre** [comment]
Regular reference filtering will be your solution then.  Can you give me a few examples though?  Because the ``stayOnDomain`` will not accept subdomains, so if you have a different domain for each country, this solution will work.

**Comment by essiembre** [comment]
@nuliknol: Do you still have an issue with this?  Can we close this ticket?

**Comment by essiembre** [comment]
Closing due to lack of feedback.
