### ISSUE TITLE
error when load config file in java

### ISSUE THREAD

**Issue by doaa-khaled** [Norconex/collector-http#263]
I get that error when trying to load the config file 

`SEVERE: Servlet.service() for servlet [tasks] in context with path [/Crawler_NORCQNEX] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoClassDefFoundError: com/norconex/collector/core/CollectorConfigLoader
	at servlets.Tasks.doPost(Tasks.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

`

and that is the code of it 
`HttpCollectorConfig config = (HttpCollectorConfig)
									new CollectorConfigLoader(HttpCollectorConfig.class).loadCollectorConfig(configFile);
							HttpCollector collector = new HttpCollector(config);`

I make sure that jar of this class is imported!!

**Comment by essiembre** [comment]
Do you have that issue when you run it standalone?  

It seems your webapp could not find that class so it looks like a classpath/classloading issue with your webapp.

As a side note, you may want to know the HTTP Collector is meant to be run in isolation/standalone (live and die with the JVM).  The crawling/parsing of some files can be quite resource intensive sometimes and running it in a webapp may compromize the webapp stability and will likely not work as you expect.  If you really want to run it in a web app, I recommend you launch the Collector as an external process.  You are of course welcome to experiment. :-)

**Comment by doaa-khaled** [comment]
Thank you for your reply, but what do you mean is that I can't use the library inside my code ?

**Comment by essiembre** [comment]
Of course not!  You can use the library with your code.  I was simply sharing what type of usage works best to save you trouble.  The problem you have (NoClassDefFoundError) is likely not one of the HTTP Collector, but rather one of the library not being found by your Java app.  You'll have to troubleshoot why your webapp (Tomcat) does not load some Jars/classes (assumming you've included all dependencies in your web app).

**Comment by doaa-khaled** [comment]
It works now! I added these jars to deployment classpath.. thanks a lot
