### ISSUE TITLE
Error when trying to crawl same job again 

### ISSUE THREAD

**Issue by doaa-khaled** [Norconex/collector-http#264]
I tried to crawl with the same configuration for second time, when trying to do that I get that exception `Execution failed for job: Crawler HTTP Collector
com.norconex.jef4.job.JobException: 2 out of 2 jobs failed in async group "Crawler HTTP Collector"
	at com.norconex.jef4.job.group.AsyncJobGroup.executeGroup(AsyncJobGroup.java:105)
	at com.norconex.jef4.job.group.AbstractJobGroup.execute(AbstractJobGroup.java:80)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:350)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:300)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:172)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:120)`

**Comment by essiembre** [comment]
Do you have more information in the logs?  The above does not say much unfortunately.   Are you running it on its own or are you re-running it in the same JVM instance?  You have to make sure you do not reusing the same instances.  The best, as suggested before, is to launch your crawl code as an external process.  If already a standalone process, feel free to attach your config to help with the troubleshooting.

**Comment by doaa-khaled** [comment]
this is the error in log file 
`java.lang.IllegalStateException: The file is locked: nio:E:\norconex-collector-http\crawler-output/crawlstore/mvstore/WikiPedia//mvstore [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:167)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	at org.h2.mvstore.MVStore.open(MVStore.java:390)
	at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStore.<init>(MVStoreCrawlDataStore.java:57)
	at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStoreFactory.createCrawlDataStore(MVStoreCrawlDataStoreFactory.java:48)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:188)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:174)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:350)
	at com.norconex.jef4.job.group.AsyncJobGroup.runJob(AsyncJobGroup.java:119)
	at com.norconex.jef4.job.group.AsyncJobGroup.access$000(AsyncJobGroup.java:44)
	at com.norconex.jef4.job.group.AsyncJobGroup$1.run(AsyncJobGroup.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
	at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
	at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at org.h2.mvstore.cache.FilePathCache$FileCache.tryLock(FilePathCache.java:158)
	at java.nio.channels.FileChannel.tryLock(Unknown Source)
	at org.h2.mvstore.FileStore.open(FileStore.java:164)
	... 14 more
Alliance Memory: 2016-06-22 14:54:38 ERROR - Execution failed for job: Alliance Memory
java.lang.IllegalStateException: The file is locked: nio:E:\norconex-collector-http\crawler-output/crawlstore/mvstore/Alliance_32_Memory//mvstore [1.4.191/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:167)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	at org.h2.mvstore.MVStore.open(MVStore.java:390)
	at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStore.<init>(MVStoreCrawlDataStore.java:57)
	at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStoreFactory.createCrawlDataStore(MVStoreCrawlDataStoreFactory.java:48)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:188)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:174)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:350)
	at com.norconex.jef4.job.group.AsyncJobGroup.runJob(AsyncJobGroup.java:119)
	at com.norconex.jef4.job.group.AsyncJobGroup.access$000(AsyncJobGroup.java:44)
	at com.norconex.jef4.job.group.AsyncJobGroup$1.run(AsyncJobGroup.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(Unknown Source)
	at sun.nio.ch.SharedFileLockTable.add(Unknown Source)
	at sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at org.h2.mvstore.cache.FilePathCache$FileCache.tryLock(FilePathCache.java:158)
	at java.nio.channels.FileChannel.tryLock(Unknown Source)
	at org.h2.mvstore.FileStore.open(FileStore.java:164)
	... 14 more`

and this is my configuration 
`<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="Crawler HTTP Collector1">
<progressDir>E:\norconex-collector-http\crawler-output\progress</progressDir><logsDir>E:\norconex-collector-http\crawler-output\logs</logsDir>
<crawlers>
<crawler id="Alliance Memory">
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true"><url>http://www.alliancememory.com/</url>
</startURLs>
<workDir>E:\norconex-collector-http\crawler-output</workDir>
<delay default="3000" ignoreRobotsCrawlDelay="true" class="com.norconex.collector.http.delay.impl.DefaultDelayResolver">
</delay>
<numThreads>15</numThreads>
<maxDepth>2</maxDepth>
<maxDocuments>-1</maxDocuments>
<keepDownloads>false</keepDownloads>
<listener class="com.norconex.collector.http.crawler.event.impl.URLStatusCrawlerEventListener"><outputDir>E:\norconex-collector-http\crawler-output</outputDir>
</listener>
<crawlDataStoreFactory class="com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStoreFactory" /><referenceFilters>
<filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude" caseSensitive="false" >jpg,gif,png,ico,css,js</filter>
</referenceFilters>
<robotsTxt ignore="false" class="com.norconex.collector.http.robot.StandardRobotsTxtProvider"/><robotsMeta ignore="false" class="com.norconex.collector.http.robot.impl.StandardRobotsMetaProvider" />
<documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher"><validStatusCodes>200</validStatusCodes><notFoundStatusCodes>404</notFoundStatusCodes></documentFetcher>
<metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher" validStatusCodes="200" />
<importer>
<postParseHandlers>
<tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger"><fields>title,keywords,description,document.reference</fields></tagger>
</postParseHandlers>
</importer>
<committer class="com.norconex.committer.core.impl.FileSystemCommitter"><directory>E:\norconex-collector-http\crawler-output\crawledFiles</directory>
</committer>
</crawler>
<crawler id="WikiPedia">
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true"><url>https://en.wikipedia.org/</url>
</startURLs>
<workDir>E:\norconex-collector-http\crawler-output</workDir>
<delay default="3000" ignoreRobotsCrawlDelay="true" class="com.norconex.collector.http.delay.impl.DefaultDelayResolver">
</delay>
<numThreads>15</numThreads>
<maxDepth>2</maxDepth>
<maxDocuments>-1</maxDocuments>
<keepDownloads>false</keepDownloads>
<listener class="com.norconex.collector.http.crawler.event.impl.URLStatusCrawlerEventListener"><outputDir>E:\norconex-collector-http\crawler-output</outputDir>
</listener>
<crawlDataStoreFactory class="com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStoreFactory" /><referenceFilters>
<filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude" caseSensitive="false" >jpg,gif,png,ico,css,js</filter>
</referenceFilters>
<robotsTxt ignore="false" class="com.norconex.collector.http.robot.StandardRobotsTxtProvider"/><robotsMeta ignore="false" class="com.norconex.collector.http.robot.impl.StandardRobotsMetaProvider" />
<documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher"><validStatusCodes>200</validStatusCodes>
<notFoundStatusCodes>404</notFoundStatusCodes>
</documentFetcher><metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher" validStatusCodes="200" /><importer><postParseHandlers><tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger"><fields>title,keywords,description,document.reference</fields>
</tagger></postParseHandlers>
</importer>
<committer class="com.norconex.committer.core.impl.FileSystemCommitter"><directory>E:\norconex-collector-http\crawler-output\crawledFiles</directory>
</committer>
</crawler>
</crawlers>
</httpcollector>`

**Comment by essiembre** [comment]
The file lock seems to indicate the problem is what I was asking you about.  There is still a previous instance of the collector/crawler still in the JVM with a hold on that file.   Have you tried lauching it as an external process instead?  If you have to launch it through your web app, you may have to find ways around the lock issue.  This thread may help you: #249.

**Comment by doaa-khaled** [comment]
yes it works as external process now.. thanks a lot
