### ISSUE TITLE
MVSTORE is locked after job complete, prevent new job from started if process not kill

### ISSUE THREAD

**Issue by xhoong** [Norconex/collector-http#336]
Hi, I'm running the crawler in my own process and would schedule a crawl based on calendar. However I got this error when restarting a completed job within the same process of last successful crawled. I trace the code and found that it is using the `StandardSitemapResolver` and the stop routine do not close the MVSTORE when the crawler stop is called. 

It would be good if the crawler can be controlled by an arbitrary Java process and do not have to stop to restart the crawler. Thanks.

When Crawler stop is called, it call the sitemap resolver stop routine, but the routine just set a boolean status and does not close the `SitemapStore`:

```
##HttpCrawler.java
public void stop(IJobStatus jobStatus, JobSuite suite) {
        super.stop(jobStatus, suite);
        if (sitemapResolver != null) {
            sitemapResolver.stop();
        }
    }
```

Exceptions:

```
java.lang.IllegalStateException: The file is locked: nio:/output/path/mvstore [1.4.192/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:167)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:344)
	at org.h2.mvstore.MVStore.open(MVStore.java:392)
	at com.norconex.collector.http.sitemap.impl.SitemapStore.<init>(SitemapStore.java:65)
	at com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory.createSitemapResolver(StandardSitemapResolverFactory.java:99)
	at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:124)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:216)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:189)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:354)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)
	at com.iotstreets.maker.services.CrawlerManager$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(CrawlerManager.scala:41)
	at com.iotstreets.maker.services.Inventory$$anon$1.run(Inventory.scala:76)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at org.h2.mvstore.cache.FilePathCache$FileCache.tryLock(FilePathCache.java:158)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.h2.mvstore.FileStore.open(FileStore.java:164)
	... 15 more
```

**Comment by essiembre** [comment]
The latest snapshot fixes this.  Keep in mind, the recommendation usually is to run the collector standalone or as an external process for increased stability.  Some document parsing require quite a bit of resources or may give unexpected results.  It may impact your main Java app if you share the same JVM.

**Comment by xhoong** [comment]
Great! I tried it and it's confirm fix. Thanks.

The crawler is running on it's process, it was wrapped in boilerplate micro service for orchestration and management. Thanks again.
