### ISSUE TITLE
Include possibly truncated reference string for mongo index

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#395]
While indexing a new crawl into my existing mongodb database (thank you), I came across an error.

## WHAT HAPPENED:

* `com.mongodb.MongoWriteException` resulted in failure to continue crawl

## DESIRED BEHAVIOR

* Store both the reference and a truncated reference
* Assure that truncated reference is unique
* Lookup by the truncated reference

## ALTERNATIVES

* Tolerate this error when indexing a document - skip that one document rather than terminating the crawl

## SUGGESTED ALGORITHM

* When the `reference` is longer than or equal to 1024, it should be truncated to 1016 and a hash of the excess added in hex encoded format.
   - Add dependency on com.sangupta murmur artifact
   - Create something that always generates the truncated_reference

## DETAILED ERROR

```
ERROR [JobSuite] Execution failed for job: MedlinePlus Monitor
com.mongodb.MongoWriteException: WiredTigerIndex::insert: key too large to index, failing  1031 { : "https://www.ncbi.nlm.nih.gov/pubmed/?term=%28pregnancy%5Bmajr%5D+OR+prenatal+care%5Bmajr%5D%29+AND+%28nutrition%5Bmajr%5D+OR+prenatal+nutritional+phys..." }
        at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:558)
        at com.mongodb.MongoCollectionImpl.update(MongoCollectionImpl.java:542)
        at com.mongodb.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:381)
        at com.norconex.collector.core.data.store.impl.mongo.MongoCrawlDataStore.queue(MongoCrawlDataStore.java:164)
        at com.norconex.collector.core.pipeline.queue.QueueReferenceStage.execute(QueueReferenceStage.java:57)
        at com.norconex.collector.core.pipeline.queue.QueueReferenceStage.execute(QueueReferenceStage.java:29)
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
        at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:273)
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLsProviders(HttpCrawler.java:238)
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:141)
        at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:130)
        at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:214)
        at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:189)
        at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
        at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:355)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
```

## REFERENCES

Apparently this has to do with the index key limit referred to in a couple places:

https://docs.mongodb.com/manual/reference/limits/#indexes
https://stackoverflow.com/questions/28681676/is-mongodb-3-0-increasing-their-key-index-limit

**Comment by danizen** [comment]
I'll try that...

**Comment by essiembre** [comment]
The latest snapshot now supports document references longer than 1024 characters using an approach similar to your suggestion.

Please confirm.

**Comment by danizen** [comment]
Again, thank you, and fast work.   I've worked around this for now using the `RegexReferenceFilter` you suggested.  I will proceed with that until next week, and then verify this after demo.

**Comment by essiembre** [comment]
I believe you confirm this to be working in a different discussion thread, but can you confirm?

**Comment by danizen** [comment]
This will be harder to verify.   My database code was pulling an URL that was not marked to be publically displayed, and so it shouldn't be included in the crawl.   So, I will have to figure out which it was with a bit of spelunking and then make a page that links to it to test.

**Comment by essiembre** [comment]
This long URL solution for Mongo is now part of the official 2.8.0 release.  Feel free to re-open if not working as expected.

**Comment by danizen** [comment]
Yes, I confirm.
