### ISSUE TITLE
NullPointerException in StandardRobotsTxtProvider

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/collector-http#396]
I am trying to migrate our Nutch environment to Norconex, but I ran into a problem: get the following error:

    ERROR [JobSuite] Execution failed for job: my_crawler
    java.lang.NullPointerException
        at com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider.getBaseURL(StandardRobotsTxtProvider.java:208)
        at com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider.getRobotsTxt(StandardRobotsTxtProvider.java:85)
        at com.norconex.collector.http.pipeline.queue.HttpQueuePipeline.getRobotsTxt(HttpQueuePipeline.java:78)
        at com.norconex.collector.http.pipeline.queue.RobotsTxtFiltersStage.findRejectingRobotsFilter(RobotsTxtFiltersStage.java:69)
        at com.norconex.collector.http.pipeline.queue.RobotsTxtFiltersStage.executeStage(RobotsTxtFiltersStage.java:46)
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:31)
        at com.norconex.collector.http.pipeline.queue.AbstractQueueStage.execute(AbstractQueueStage.java:24)
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
        at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:273)
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLsSeedFiles(HttpCrawler.java:173)
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:140)
        at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:130)
        at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:214)
        at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:189)
        at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
        at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:355)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)

Please find the full log and XML config file attached (some things omitted for privacy).

[virhelogi 2017-09-21.txt](https://github.com/Norconex/collector-http/files/1321467/virhelogi.2017-09-21.txt)
[norconex config github.txt](https://github.com/Norconex/collector-http/files/1321472/norconex.config.github.txt)

**Comment by ronjakoi** [comment]
[norconex config github.txt](https://github.com/Norconex/collector-http/files/1321472/norconex.config.github.txt)

**Comment by essiembre** [comment]
Will investigate.  In the meantime you can disable robot.txt support in your config.  Can you share a copy of your robots.txt file?

**Comment by essiembre** [comment]
I found the exact cause.  Your startURLs/urlsFile has blank lines in it.  Until this is fixed, you can remove them and it should be OK.

**Comment by essiembre** [comment]
The [latest snapshot](https://www.norconex.com/collectors/collector-http/download) now has the fix for this.  Please confirm.

In addition to blank lines in a URL seed file no longer causing issues, lines starting with # (for comments) are now ignored.

**Comment by ronjakoi** [comment]
Confirmed, bug is fixed in latest snapshot.
