### ISSUE TITLE
Trying to start 2.0.1 with old configs.

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#45]
Hello!

Haven't visited you for a long time :)

I cleaned workdir and tried to launch the collector via command line getting such exceptions:

```
WARN  [ConfigurationUtil] Could not instantiate object from configuration for node: crawlerDefaults key: robotsTxt
com.norconex.commons.lang.config.ConfigurationException: This class could not be instantiated: "com.norconex.collector.http.robot.impl.DefaultRobotsTxtProvider".
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:177)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:292)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:258)
	at com.norconex.collector.http.crawler.HttpCrawlerConfig.loadCrawlerConfigFromXML(HttpCrawlerConfig.java:285)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:325)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:123)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:72)
	at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:176)
	at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:65)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: java.lang.ClassNotFoundException: com.norconex.collector.http.robot.impl.DefaultRobotsTxtProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:175)
	... 10 more
WARN  [ConfigurationUtil] Could not instantiate object from configuration for node: crawlerDefaults key: robotsMeta
com.norconex.commons.lang.config.ConfigurationException: This class could not be instantiated: "com.norconex.collector.http.robot.impl.DefaultRobotsMetaProvider".
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:177)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:292)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:258)
	at com.norconex.collector.http.crawler.HttpCrawlerConfig.loadCrawlerConfigFromXML(HttpCrawlerConfig.java:309)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:325)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:123)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:72)
	at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:176)
	at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:65)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: java.lang.ClassNotFoundException: com.norconex.collector.http.robot.impl.DefaultRobotsMetaProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:175)
	... 10 more
Exception in thread "main" java.lang.NoClassDefFoundError: com/norconex/committer/AbstractMappedCommitter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:175)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:292)
	at com.norconex.commons.lang.config.ConfigurationUtil.newInstance(ConfigurationUtil.java:258)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:318)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:123)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:83)
	at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:176)
	at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:65)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: java.lang.ClassNotFoundException: com.norconex.committer.AbstractMappedCommitter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

```

What I'm doing wrong and are old configs good for a new version of the collector?

**Comment by essiembre** [comment]
2.x is a major release with its config options not back-ward compatible on many front.  It is the same product overall, but many improvements and additions were made and a few names were changed or repackaged to favor consistency.   When you get such errors I suggest you check the configuration page for the new names (including a few tag name changes): http://www.norconex.com/collectors/collector-http/configuration

In your case: 

* DefaultRobotsTxtProvider is now com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider
* DefaultRobotsMetaProvider is now com.norconex.collector.http.robot.impl.StandardRobotsMetaProvider

The importer module has changed as well.  All transformers, tagger, etc. now have "handler" in their package name now.  This page was updated to reflect the changes: http://www.norconex.com/collectors/importer/configuration

If you have more that you cannot figure out, do not hesitate to ask and I will map them all for you.

**Comment by AntonioAmore** [comment]
Thank you for the quick response. I updated my configuration files to reflect changes of v. 2.0.

Now I have such exception:

```
WARN  [StandardRobotsTxtProvider] Not able to obtain robots.txt at: www.site.com/robots.txt
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider.getRobotsTxt(StandardRobotsTxtProvider.java:77)
	at com.norconex.collector.http.pipeline.queue.HttpQueuePipelineContext.<init>(HttpQueuePipelineContext.java:41)
	at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:162)
	at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:121)
	at com.norconex.collector.http.crawler.HttpCrawler.prepareExecution(HttpCrawler.java:111)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:195)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:169)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:336)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:286)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:158)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:114)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:69)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:69)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
	... 17 more
```

I'm sure the file exists as can load it manually. What may cause such exception?

**Comment by AntonioAmore** [comment]
I'm sure that's something wrong with configuration, or a library is absient, as the collector can't download any page causing a similar exception.

**Comment by davidgaulin** [comment]
Quickly looking at the exception (I haven’t checked the code at all).  Could you confirm the URL you are passing in your config file?

 

…

Caused by: org.apache.http.ProtocolException

…

at:  <http://www.site.com/robots.txt> www.site.com/robots.txt

 

 

Are you missing the http:// part?

**Comment by AntonioAmore** [comment]
Yes, I weren't careful enough and missed http:// in an url. I propose to put somewhere in docs that it is important.

Thank you a lot, everything works perfectly.
