### ISSUE TITLE
[PhantomJSDocumentFetcher] (2.8.0) NPE in createPhantomJSCommand()

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#490]
Hi,
It seems there's a regression with HttpCollector 2.8.0 (not reproduced in 2.7.1).
An Ajax crawl throws Null Pointer Exception :
```
java.lang.NullPointerException
	at com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher.createPhantomJSCommand(PhantomJSDocumentFetcher.java:1030)
	at com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher.fetchPhantomJSDocument(PhantomJSDocumentFetcher.java:799)
	at com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher.fetchDocument(PhantomJSDocumentFetcher.java:773)
	at com.norconex.collector.http.pipeline.importer.DocumentFetcherStage.executeStage(DocumentFetcherStage.java:42)
```
on the line:
```
   cmdArgs.add(argQuote(                              // phantom.js arg 7
                screenshotDimensions.getWidth() + "x"
              + screenshotDimensions.getHeight()));       
```

**Comment by sylvainroussy** [comment]
Closing because 2.8.1 fix it: 
```
Fixed NullPointerException when using PhantomJSDocumentFetcher without          specifying any "screenshotDimensions".
```
