### ISSUE TITLE
Forms Authentication failing

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#530]
Hi,
Forms authentication does not seem to work..

here is the public site: 
url to be crawled: https://s1.demo.opensourcecms.com/drupal/admin/appearance
https://s1.demo.opensourcecms.com/drupal/user/login
Username: opensourcecms
Password: opensourcecms

while this is basically similar to issue 500, the soln provided there seems to be giving me some new errors:

Exception in thread "main" java.lang.NoSuchMethodError: com.norconex.commons.lang.config.XMLConfigurationUtil.getNullableDimension(Lorg/apache/commons/configuration/HierarchicalConfiguration;Ljava/lang/String;Ljava/awt/Dimension;)Ljava/awt/Dimension;
	at com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher.loadFromXML(PhantomJSDocumentFetcher.java:1202)
	at com.norconex.commons.lang.config.XMLConfigurationUtil.loadFromXML(XMLConfigurationUtil.java:445)
	at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:206)
	at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:273)
	at com.norconex.commons.lang.config.XMLConfigurationUtil.newInstance(XMLConfigurationUtil.java:258)
	at com.norconex.collector.http.crawler.HttpCrawlerConfig.loadCrawlerConfigFromXML(HttpCrawlerConfig.java:584)
	at com.norconex.collector.core.crawler.AbstractCrawlerConfig.loadFromXML(AbstractCrawlerConfig.java:395)
	at com.norconex.commons.lang.config.XMLConfigurationUtil.loadFromXML(XMLConfigurationUtil.java:445)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfig(CrawlerConfigLoader.java:119)
	at com.norconex.collector.core.crawler.CrawlerConfigLoader.loadCrawlerConfigs(CrawlerConfigLoader.java:79)
	at com.norconex.collector.core.AbstractCollectorConfig.loadFromXML(AbstractCollectorConfig.java:304)
	at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:78)
	at com.norconex.collector.core.AbstractCollectorLauncher.loadCommandLineConfig(AbstractCollectorLauncher.java:141)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:92)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:74)

Has there been any updates to the standard forms authentication? I am using 2.8.1

Thanks

**Comment by essiembre** [comment]
Did you overwrite your existing installation with 2.8.1 by any chance?  The method it complains of not finding was in fact introduced in Norconex Commons Lang version 1.14.0 which is packaged with Norconex HTTP Collector since version 2.8.0 (or higher versions).

Check in the "lib" folder to make sure you do not have duplicate jars (same name different versions). or manually upgrade to Norconex Commons Lang to 1.15.0 if you have an older one for some reason.

**Comment by dtcyad1** [comment]
Hi Pascal,
Thanks yes - I probably did overwrite some jars.

Where you able to test the Forms Authentication issue?
Thanks

**Comment by dtcyad1** [comment]
Hi Pascal,

i was able to extend the HttpClientFactory as suggested in some other posts. Thanks for your help.
