### ISSUE TITLE
The system cannot find the ".....-add.cntnt" file specified

### ISSUE THREAD

**Issue by ciroppina** [Norconex/collector-http#566]
Dears,
I am running a connector instance configured with about 40 active crawlers. Sometimes, in the log I read:
java.io.FileNotFoundException: D:\connettori_norconex\norconex-collector-http-2.8.1\.\tasks-output\unified_PRL\committer-queue\2019\02-19\05\17\59\1550593079606000000-add.cntnt (The system cannot find the file specified)

The un-found file is one of those generated by the collector, and temporarily saved to the committer-queue directory

I attach the whole config file here below
[unified_PRL-idolcfs-config.zip](https://github.com/Norconex/collector-http/files/2881040/unified_PRL-idolcfs-config.zip)

The fragment of log is the following:
```
com.norconex.committer.core.CommitterException: Could not obtain content stream for D:\connettori_norconex\norconex-collector-http-2.8.1\.\tasks-output\unified_PRL\committer-queue\2019\02-19\05\17\59\1550593079606000000-add.cntnt
	at com.norconex.committer.core.FileAddOperation.getContentStream(FileAddOperation.java:129)
	at com.norconex.committer.idol.IdolCommitter.buildCfsXmlBatchContent(IdolCommitter.java:604)
	at com.norconex.committer.idol.IdolCommitter.dreAddData(IdolCommitter.java:420)
	at com.norconex.committer.idol.IdolCommitter.commitBatch(IdolCommitter.java:285)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAndCleanBatch(AbstractBatchCommitter.java:179)
	at com.norconex.committer.core.AbstractBatchCommitter.cacheOperationAndCommitIfReady(AbstractBatchCommitter.java:208)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAddition(AbstractBatchCommitter.java:143)
	at com.norconex.committer.core.AbstractFileQueueCommitter.commit(AbstractFileQueueCommitter.java:222)
	at com.norconex.committer.core.AbstractCommitter.commitIfReady(AbstractCommitter.java:146)
	at com.norconex.committer.core.AbstractCommitter.add(AbstractCommitter.java:97)
	at com.norconex.collector.core.pipeline.committer.CommitModuleStage.execute(CommitModuleStage.java:34)
	at com.norconex.collector.core.pipeline.committer.CommitModuleStage.execute(CommitModuleStage.java:27)
	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
	at com.norconex.collector.http.crawler.HttpCrawler.executeCommitterPipeline(HttpCrawler.java:379)
	at com.norconex.collector.core.crawler.AbstractCrawler.processImportResponse(AbstractCrawler.java:600)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:541)
	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:419)
	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:820)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: D:\connettori_norconex\norconex-collector-http-2.8.1\.\tasks-output\unified_PRL\committer-queue\2019\02-19\05\17\59\1550593079606000000-add.cntnt (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.norconex.committer.core.FileAddOperation.getContentStream(FileAddOperation.java:127)
	... 20 more
```

**Comment by essiembre** [comment]
Are you using multiple crawlers?  If so, make sure each has a different "queueDir".  Otherwise, it is possible they'll try to commit the same files and this could happen.

**Comment by ciroppina** [comment]
Thank You v.m. Pascal Essiembre, 
Your suggestion closes this issue

**Comment by ciroppina** [comment]
One last question, plese:

how to override the <queueDir> setting?
I have a <committer> tag with the <queueDir> child-tag in the <crawlerDefaults> seciotn of my collector config file. That file also includes about 40 <crawlers><crawler>...</crawler></crawlers>

I tried to change the 'queueDir' in one of the 40 crawlers, by simply setting a tag as follows:
```
<committer class="com.norconex.committer.idol.IdolCommitter">
	<!-- (optional path where to queue files) -->
	<queueDir>./tasks-output/rl_agricoltura/committer-queue</queueDir>
</committer>
``` 
but looks like it does not work. Is it required to copy the whole <committer> settings within each <crawser> section? [I hope no]

**Comment by essiembre** [comment]
There are a few ways around this.  For instance, given the configurations are template-driven using Apache Velocity, you can define a "macro" at the top and have it print the committer section with only the path changing.  For example:
```xml
#macro( committer $queueDir )
<committer class="com.norconex.committer.idol.IdolCommitter">
    <!-- Common stuff here -->
    <queueDir>$queueDir</queueDir>
</committer>
#end
```

You can then have a one liner for each of your crawler:

#committer("./tasks-output/rl_agricoltura/committer-queue")

Given this ticket is closed, please open new tickets for any new questions/issues.
