### ISSUE TITLE
Java Null Pointer Exception when a link points to a page that no longer exist

### ISSUE THREAD

**Issue by martinfou** [Norconex/collector-http#71]
Here is an example of the error message the collector generates when it encounters a link that points to a page that no longer exist. 

ERROR [AbstractCrawler] Norconex Minimum Test Page: Could not process document: http://localhost:8080/test-web-site/page3.jsp (null)
java.lang.NullPointerException
        at com.norconex.collector.http.pipeline.importer.HttpImporterPipelineUtil.enhanceHTTPHeaders(HttpImporterPipelineUtil.java:67)
        at com.norconex.collector.http.pipeline.importer.HttpImporterPipeline$DocumentFetcherStage.executeStage(HttpImporterPipeline.java:150)
        at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:31)
        at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:24)
        at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:90)
        at com.norconex.collector.http.crawler.HttpCrawler.executeImporterPipeline(HttpCrawler.java:213)
        at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:480)
        at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:376)
        at com.norconex.collector.core.crawler.AbstractCrawler$ProcessURLsRunnable.run(AbstractCrawler.java:638)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by essiembre** [comment]
Several fixes were recently made and a [snapshot release](http://www.norconex.com/collectors/collector-http/download) has been made (2015-04-06).  Please try it and let me know.   Make sure to install it in a clean location to prevent having the same Jars with different versions.

**Comment by essiembre** [comment]
[Norconex HTTP Collector 2.1.0](http://www.norconex.com/collectors/collector-http/download) was released. Closing.
