### ISSUE TITLE
Committing does not working

### ISSUE THREAD

**Issue by anagas** [Norconex/collector-http#735]
Hello

We are using norconex since months but since 1 Week we are not able to to commit the documents...

We are seeing 2 errors in the logs first one is a certificate issue and the second one is a acl issue.

```
Crawler finishing: committing documents.
INFO  [AbstractFileQueueCommitter] Committing 544 files
INFO  [GoogleCloudSearchCommitter] Starting up!
Feb 04, 2021 7:50:00 AM com.google.enterprise.cloudsearch.sdk.BatchRequestService$SnapshotRunnable getGoogleJsonError
WARNING: Retrying request failed with exception:
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:394)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:493)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
	at com.google.api.client.googleapis.batch.BatchRequest$BatchInterceptor.intercept(BatchRequest.java:300)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
	at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:241)
	at com.google.enterprise.cloudsearch.sdk.BatchRequestService$BatchRequestHelper.executeBatchRequest(BatchRequestService.java:447)
	at com.google.enterprise.cloudsearch.sdk.BatchRequestService$SnapshotRunnable.execute(BatchRequestService.java:308)
	at com.google.enterprise.cloudsearch.sdk.BatchRequestService$SnapshotRunnable.run(BatchRequestService.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	... 31 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 37 more
```

```
WARNING: Request failed with error {code=504, message=PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}
INFO  [AbstractCrawler] Prod Update: Crawler executed in 5 minutes 29 seconds.
INFO  [SitemapStore] Prod Update: Closing sitemap store...
ERROR [JobSuite] Execution failed for job: ProdUpdate
com.google.enterprise.cloudsearch.sdk.StartupException: Unable to upload default ACL.
	at com.google.enterprise.cloudsearch.sdk.indexing.DefaultAcl.<init>(DefaultAcl.java:220)
	at com.google.enterprise.cloudsearch.sdk.indexing.DefaultAcl.<init>(DefaultAcl.java:93)
	at com.google.enterprise.cloudsearch.sdk.indexing.DefaultAcl$Builder.build(DefaultAcl.java:466)
	at com.google.enterprise.cloudsearch.sdk.indexing.DefaultAcl.fromConfiguration(DefaultAcl.java:266)
	at com.norconex.committer.googlecloudsearch.GoogleCloudSearchCommitter$Helper.initDefaultAclFromConfig(GoogleCloudSearchCommitter.java:400)
	at com.norconex.committer.googlecloudsearch.GoogleCloudSearchCommitter.init(GoogleCloudSearchCommitter.java:195)
	at com.norconex.committer.googlecloudsearch.GoogleCloudSearchCommitter.commitBatch(GoogleCloudSearchCommitter.java:226)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAndCleanBatch(AbstractBatchCommitter.java:179)
	at com.norconex.committer.core.AbstractBatchCommitter.cacheOperationAndCommitIfReady(AbstractBatchCommitter.java:208)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAddition(AbstractBatchCommitter.java:143)
	at com.norconex.committer.core.AbstractFileQueueCommitter.commit(AbstractFileQueueCommitter.java:222)
	at com.norconex.collector.core.crawler.AbstractCrawler.execute(AbstractCrawler.java:274)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:228)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:184)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:354)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:293)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:166)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:150)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:74)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException
	at com.google.enterprise.cloudsearch.sdk.AsyncRequest$SettableFutureCallback.onFailure(AsyncRequest.java:180)
	at com.google.enterprise.cloudsearch.sdk.BatchRequestService$SnapshotRunnable.onFailure(BatchRequestService.java:323)
	at com.google.enterprise.cloudsearch.sdk.BatchRequestService$SnapshotRunnable.lambda$run$0(BatchRequestService.java:241)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.google.enterprise.cloudsearch.sdk.BatchRequestService$SnapshotRunnable.run(BatchRequestService.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Like I said we did not change our configuration. How is it possible that the commiting documents is not possible anymore?

**Comment by somphouang** [comment]
Have you updated Java runtime by any chance?

**Comment by anagas** [comment]
@somphouang Yes, Java was updated on January 28th to 1.8.0_275

**Comment by OkkeKlein** [comment]
Certificate no longer valid?

**Comment by essiembre** [comment]
Hello @anagas, with your new version of Java, it is very well possible it uses a new key store supporting different CA authorities.

The recommendation would be to add the missing certificate to the Java key store.  There are several examples online on how to achieve this, such as this one: https://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed/

**Comment by anagas** [comment]
Hello @essiembre we can crawl all our pages so this means the certificates for the crawled pages are ok. Its failing at the commit but it does not show which pages has this issue. Do you know which page is requested at the commit for cloud search?

**Comment by somphouang** [comment]
@anagas , the crawled pages domain are not the same domain as where you are committing to.  If possible, are you able to verify your Cloud Search domain from @essiembre comment hint above?  There are some hints here as well https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

**Comment by anagas** [comment]
Hello @somphouang 

I tried to import the certicates and also copied the old cacerts from the old version to the new one but nothing changed.

**Comment by essiembre** [comment]
Hello @anagas, is it possible for you to try with the previous version of Java you had as a test?  Another thing to try is to point explicitly to the trust store you want to reference.  You can modify the collector launch script to do so. E.g.: 

```
java -Djavax.net.debug=all -Djavax.net.ssl.trustStore=YourTrustStore
```

Else, since the exception comes from the Google Cloud Search Committer, I suggest you report your issue [here](https://github.com/google-cloudsearch/norconex-committer-plugin/issues) in case it is something Google is aware of and can fix.

It seems you are not the only one with this issue: https://github.com/google-cloudsearch/norconex-committer-plugin/issues/19

Maybe you can try using the latest `google-cloudsearch-indexing-connector-sdk` dependency in case they addressed this issue already.
