### ISSUE TITLE
ElasticSearch Committer Error

### ISSUE THREAD

**Issue by jacksonp2008** [Norconex/collector-http#740]
Running the lastest 3.0.0 M1 with elasticsearch 5.0.0 m1

Per the doc, it seems like typename should be there:  https://opensource.norconex.com/committers/elasticsearch/v4/configuration

But it may have changed with 5?

```
      <committers>
        <committer class="com.norconex.committer.elasticsearch.ElasticsearchCommitter">
          <nodes>https://searcdfhdhdhdhdhdhdhdhdhhdhdh1.es.amazonaws.com:443</nodes>
          <indexName>docs</indexName>
          <typeName>docs</typeName>
          <targetContentField>fs_content</targetContentField>
          <fixBadIds>true</fixBadIds>
        </committer>
      </committers>
```

With this config,  

```
./collector-http.sh start -c forescout/docs/docs-config/docs-config.xml 

1 XML configuration errors detected:

[XML] StartCommand: cvc-complex-type.2.4.a: Invalid content was found starting with element 'typeName'. One of '{restrictTo, fieldMappings, queue, ignoreResponseErrors, discoverNodes, dotReplacement, credentials, jsonFieldsPattern, connectionTimeout, socketTimeout, fixBadIds, sourceIdField, targetContentField}' is expected.
```

If I remove "typeName", it errors when trying to commit to ES:

```
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [https://search-seservices-qyt22kq34vaaadaz465jecxama.us-east-1.es.amazonaws.com:443], URI [/_bulk], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;"},"status":400}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283) ~[elasticsearch-rest-client-7.8.1.jar:7.8.1]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261) ~[elasticsearch-rest-client-7.8.1.jar:7.8.1]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-7.8.1.jar:7.8.1]
	at com.norconex.committer.elasticsearch.ElasticsearchCommitter.commitBatch(ElasticsearchCommitter.java:506) ~[norconex-committer-elasticsearch-5.0.0-M1.jar:5.0.0-M1]
	... 23 more

```

**Comment by essiembre** [comment]
Hello @jacksonp2008, 

You are correct that "typeName" is no longer supported, in line with Elasticsearch's evolving API.  

Which version of Elasticsearch are you using?  Support for type has been deprecated in Elasticsearch 6.x and effectively [removed starting from Elasticsearch 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html).  

You may consider upgrading your version of Elasticsearch.

You can find the Committer version 5 documentation from the [JavaDoc:](https://opensource.norconex.com/committers/elasticsearch/v5/apidocs/com/norconex/committer/elasticsearch/ElasticsearchCommitter.html).

**Comment by jacksonp2008** [comment]
Version 6.3 via AWS. (6.8 is the latest they offer)   Can I use an older committer with 3.0.0?

**Comment by essiembre** [comment]
Which zone are you in?  Last time I checked, AWS Elasticsearch service was offering up to 7.9, as described [here](https://aws.amazon.com/elasticsearch-service/faqs/).

Unfortunately, older committers are not compatible with 3.0.0.  

We can make it a feature request to support version 6.x of Elasticsearch but you can likely upgrade Elasticsearch faster.

**Comment by jacksonp2008** [comment]
Unfortunately I can't easily upgrade beyond 6 as there are a lot of tools using ES right now and we would have to do a lot of testing.  I may have to find another way using some of your previous recommendations from https://github.com/Norconex/collector-http/issues/739

I'll try the Phantomjs approach next.  Thank-you Pacal
