### ISSUE TITLE
Is MongoDB required?

### ISSUE THREAD

**Issue by jettro** [Norconex/collector-http#748]
Hi, I am experimenting with the http collector, using the latest snapshot I always see a MongoDB connection being created. is that required? Can I configure something to switch it off?

**Comment by essiembre** [comment]
MongoDB is an optional data store implementation.  The default uses MVStore on local disks.  Are you using it as your `<crawlDataStoreEngine>`?  If not, there are no reasons for it to connect  Can you share the corresponding logs?

Does this happen when you run unit tests?  There are tests for it, which may be why.

**Comment by jettro** [comment]
I am running Norconex within a spring boot application. Configuration is purely java.

```
        HttpCollectorConfig collectorConfig = new HttpCollectorConfig();
        collectorConfig.setId(norconexProperties.getName() + "Collector");

        HttpCrawlerConfig crawlerConfig = new HttpCrawlerConfig();
        crawlerConfig.setId(norconexProperties.getName() + "Crawler");
        crawlerConfig.setStartURLsProviders();
        crawlerConfig.setStartURLs(norconexProperties.getStartUrls());
        URLCrawlScopeStrategy strategy = new URLCrawlScopeStrategy();
        strategy.setStayOnDomain(true);

        crawlerConfig.setUrlCrawlScopeStrategy(strategy);
        crawlerConfig.setMaxDepth(1);
        crawlerConfig.setDataStoreEngine(new MVStoreDataStoreEngine());
        ElasticsearchCommitter elasticsearchCommitter = new ElasticsearchCommitter();
        elasticsearchCommitter.setNodes(norconexProperties.getElasticsearchNodes());
        elasticsearchCommitter.setIndexName(norconexProperties.getElasticsearchIndexName());
        crawlerConfig.setCommitters(new JSONFileCommitter(), elasticsearchCommitter);

        crawlerConfig.addEventListeners(event -> {
            System.out.println("EVENT: " + event.getName() + ",  " + event.getMessage());
        });

        collectorConfig.setCrawlerConfigs(crawlerConfig);

        this.collector = new HttpCollector(collectorConfig);

```
When starting the spring boot app, I see this message in the log.

```
15:23:31.211 [main] INFO  Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
15:23:31.208 [cluster-ClusterId{value='607d845352c0206a8dd25325', description='null'}-localhost:27017] INFO  cluster - Exception in monitor thread while connecting to server localhost:27017
 com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70) ~[mongodb-driver-core-4.1.2.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:143) ~[mongodb-driver-core-4.1.2.jar:?]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188) [mongodb-driver-core-4.1.2.jar:?]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144) [mongodb-driver-core-4.1.2.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:591) ~[?:?]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:78) ~[mongodb-driver-core-4.1.2.jar:?]
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79) ~[mongodb-driver-core-4.1.2.jar:?]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[mongodb-driver-core-4.1.2.jar:?]
	... 4 more


```

**Comment by jettro** [comment]
Turns out, spring boot enables the autoconfiguration for mongo, disabling this solved my problem.
