### ISSUE TITLE
mysql problem when starting crawl

### ISSUE THREAD

**Issue by jettro** [Norconex/collector-http#749]
Hi,
I am experimenting with the latest snapshot of 3.0.0 and running into an issue with the JdbcDataStoreEngine. When starting a scroll I run into the following stacktrace. Do you have any idea what I can do to change this behavior and use the scroll with MySQL?

`2021-04-15 11:59:11.231 ERROR 99655 --- [ollector Config] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.norconex.collector.core.store.DataStoreException: Could not create table 'My_32_Collector_32_Config_95_My_32_Crawler_32_Config_95__storetypes'.] with root cause

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CLOB, PRIMARY KEY (id) )' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1333) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2106) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1243) ~[mysql-connector-java-8.0.23.jar:8.0.23]
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar:na]
	at com.norconex.collector.core.store.impl.jdbc.JdbcDataStore.createTable(JdbcDataStore.java:188) ~[norconex-collector-core-2.0.0-20210329.061715-21.jar:2.0.0-SNAPSHOT]
	at com.norconex.collector.core.store.impl.jdbc.JdbcDataStore.<init>(JdbcDataStore.java:57) ~[norconex-collector-core-2.0.0-20210329.061715-21.jar:2.0.0-SNAPSHOT]
	at com.norconex.collector.core.store.impl.jdbc.JdbcDataStoreEngine.init(JdbcDataStoreEngine.java:134) ~[norconex-collector-core-2.0.0-20210329.061715-21.jar:2.0.0-SNAPSHOT]
	at com.norconex.collector.core.crawler.Crawler.initCrawler(Crawler.java:299) ~[norconex-collector-core-2.0.0-20210329.061715-21.jar:2.0.0-SNAPSHOT]
	at com.norconex.collector.core.crawler.Crawler.start(Crawler.java:234) ~[norconex-collector-core-2.0.0-20210329.061715-21.jar:2.0.0-SNAPSHOT]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1083) ~[na:na]
	at com.norconex.collector.core.Collector.start(Collector.java:183) ~[norconex-collector-core-2.0.0-20210329.061715-21.jar:2.0.0-SNAPSHOT]
	at eu.luminis.aws.norconex.NorconexService.start(NorconexService.java:22) ~[classes/:an]
...

**Comment by jettro** [comment]
Any idea on this one? Have an idea what JDBC driver plus database combination does work?

**Comment by essiembre** [comment]
Can you try the latest v3 snapshot that was just made?  It has better support for different databases and should work out-of-the-box with MySQL.  In case you still have data type-related errors, you can now overwrite the default data types being used by this data store engine (but you should not need it for MySQL):

```xml
<dataStoreEngine class="JdbcDataStoreEngine" />

  ...

  <dataTypes>
    <varchar   use="(equivalent data type for your database)" />
    <timestamp use="(equivalent data type for your database)" />
    <text      use="(equivalent data type for your database)" />
  </dataTypes>
</dataStoreEngine>
```

**Comment by jettro** [comment]
I Will test it again, the main focus now is DynamoDB though, need some time :-)
