### ISSUE TITLE
java.io.UTFDataFormatException: encoded string too long

### ISSUE THREAD

**Issue by nAoxide** [Norconex/collector-http#772]
Hi!
I keep getting this message whenever I start the crawler..
what is it about? and how do I prevent the program from stopping after that message shows up?
`java.io.UTFDataFormatException: encoded string too long: 71234 bytes
        at java.io.DataOutputStream.writeUTF(Unknown Source)
        at java.io.RandomAccessFile.writeUTF(Unknown Source)
        at com.norconex.jef4.suite.JobSuite.writeJobSuiteIndex(JobSuite.java:627)
        at com.norconex.jef4.suite.JobSuite.initialize(JobSuite.java:510)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:275)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:166)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:150)
        at naoxide.numberspider.Spider$5.run(Spider.java:583)
        at java.lang.Thread.run(Unknown Source)`

**Comment by essiembre** [comment]
I suspect maybe you have very long path and/or collector/crawler "id" names in your XML config. Which version are you using?  Can you reproduce at will?  If so, can you share a reproducible config?

**Comment by nAoxide** [comment]
I have made the names a little bit shorter and it worked!
I never thought that would be an issues..
anyway, I do give the tool lots of links to discover and crawl. Isn't there anything I can do to make it accept big amount of links?
I had to give it chunks of my big list..

**Comment by essiembre** [comment]
What issue do you have with "big amount" of links?  If you mean performance, you can reduce the default `<delay>`, increase the number of threads, etc.   If you want to crawl millions of websites in a short time, it may be too much for a single instance. You will likely have to look at having multiple collectors/crawlers on distributed hardware or something like that. Depends on what you are after and you may have to benchmark. You can also look at using a distributed crawl store engine, like the MongoDB one if you run into scalability issues with the default MVStore one.
