### ISSUE TITLE
GenericSitemapResolver - Cannot fetch sitemap: <sitemap> (null)

### ISSUE THREAD

**Issue by adesso-david** [Norconex/collector-http#803]
Hi everybody!

I'm getting following error while trying to crawl my companies website:

```
14:03:23.303 [adesso-de] ERROR com.norconex.collector.http.sitemap.impl.GenericSitemapResolver - Cannot fetch sitemap: https://www.adesso.de/de/sitemap-de-de.xml (null)
java.lang.NullPointerException: null
        at com.norconex.collector.http.sitemap.impl.GenericSitemapResolver.resolveSitemap(GenericSitemapResolver.java:294) ~[norconex-collector-http-3.0.1.jar:3.0.1]
        at com.norconex.collector.http.sitemap.impl.GenericSitemapResolver.resolveSitemaps(GenericSitemapResolver.java:222) ~[norconex-collector-http-3.0.1.jar:3.0.1]
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLsSitemaps(HttpCrawler.java:249) ~[norconex-collector-http-3.0.1.jar:3.0.1]
        at com.norconex.collector.http.crawler.HttpCrawler.queueStartURLs(HttpCrawler.java:184) ~[norconex-collector-http-3.0.1.jar:3.0.1]
        at com.norconex.collector.http.crawler.HttpCrawler.beforeCrawlerExecution(HttpCrawler.java:167) ~[norconex-collector-http-3.0.1.jar:3.0.1]
        at com.norconex.collector.core.crawler.Crawler.start(Crawler.java:265) ~[norconex-collector-core-2.0.1.jar:2.0.1]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) [?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) [?:?]
        at com.norconex.collector.core.Collector.start(Collector.java:196) [norconex-collector-core-2.0.1.jar:2.0.1]
        at com.norconex.collector.core.cmdline.StartCommand.runCommand(StartCommand.java:48) [norconex-collector-core-2.0.1.jar:2.0.1]
        at com.norconex.collector.core.cmdline.AbstractSubCommand.call(AbstractSubCommand.java:143) [norconex-collector-core-2.0.1.jar:2.0.1]
        at com.norconex.collector.core.cmdline.AbstractSubCommand.call(AbstractSubCommand.java:45) [norconex-collector-core-2.0.1.jar:2.0.1]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine.access$1300(CommandLine.java:145) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at picocli.CommandLine.execute(CommandLine.java:2078) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
        at com.norconex.collector.core.cmdline.CollectorCommandLauncher.launch(CollectorCommandLauncher.java:46) [norconex-collector-core-2.0.1.jar:2.0.1]
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:57) [norconex-collector-http-3.0.1.jar:3.0.1]
```
        
I had an older config laying around, since we used a crawler with the v2.9.0 http collector before and i updated the config for v3.0.1.
The old collector worked fine. I checked out the line of code and it appears, that GenericSitemapResolver can't read the content-type of the response. (Maybe because the response of the [sitemap](https://www.adesso.de/de/sitemap-de-de.xml) uses lowercase letters for metadata, but the code only checks for `Content-Type`)

My config regarding the sitemap is following:

```xml
<startURLs stayOnDomain="true">
        <sitemap>https://www.adesso.de/de/sitemap-de-de.xml</sitemap>
</startURLs>
<sitemapResolver ignore="false"/>
```

Is it a bug in the code or did i mess up my config?

**Comment by essiembre** [comment]
Turns out to be a bug. Please try the latest snapshot I just made.  An attempt was made to detect the content type to know whether the sitemap is compressed (gzipped).  In your case, it was not detected (so null).  Now it will treat such cases as if it was uncompressed and should proceed like normal.

**Comment by adesso-david** [comment]
Hi essiembre,
thank you a lot for your fast respond and fix! It seems working fine now.
