### ISSUE TITLE
Issue with WebDriverHttpFetcher: NoSuchMethodError

### ISSUE THREAD

**Issue by lg255** [Norconex/collector-http#810]
Hi!

First, I really like this lib! It works really great!

But now, I have an issue using the WebDriverHttpFetcher. My app is running as a Spring Boot (2.7.0) application with Java 17 on a Windows 11 machine. The build tool is Maven.

When using the WebDriverHttpFetcher I get the following error:

`java.lang.NoSuchMethodError: 'org.openqa.selenium.chrome.ChromeOptions org.openqa.selenium.chrome.ChromeOptions.setHeadless(boolean)'`

My setup code is the following:

```java
WebDriverHttpFetcherConfig fetcherConfig = new WebDriverHttpFetcherConfig();
fetcherConfig.setBrowser(Browser.CHROME);
fetcherConfig.setBrowserPath(Path.of("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"));
fetcherConfig.setDriverPath(Path.of("C:\\[...]\\chromedriver.exe"));
WebDriverHttpFetcher fetcher = new WebDriverHttpFetcher(fetcherConfig);
crawlerConfig.setHttpFetchers(fetcher);
```

I have no other Selenium dependencies whatsoever.

I would really appreciate any support!

Thank you very much in advance and all the best!

**Comment by ohtwadi** [comment]
Hello!
Could you please provide the full stack trace?

**Comment by lg255** [comment]
Hello!

Thank you very much for coming back at me. The full stack trace looks like this:

````java
2023-02-04 09:03:46,036 INFO [collector-1] c.n.c.c.Collector [Collector.java:179] 
 _   _  ___  ____   ____ ___  _   _ _______  __
| \ | |/ _ \|  _ \ / ___/ _ \| \ | | ____\ \/ /
|  \| | | | | |_) | |  | | | |  \| |  _|  \  / 
| |\  | |_| |  _ <| |__| |_| | |\  | |___ /  \ 
|_| \_|\___/|_| \_\\____\___/|_| \_|_____/_/\_\

============== C O L L E C T O R ==============

Collector and main components:

Collector:          Norconex HTTP Collector 3.0.1 (Norconex Inc.)
Collector Core:     Norconex Collector Core 2.0.1 (Norconex Inc.)
Importer:           Norconex Importer 3.0.0 (Norconex Inc.)
Lang:               Norconex Commons Lang 2.0.1 (Norconex Inc.)
Committer(s):
  Core:             Norconex Committer Core 3.0.0 (Norconex Inc.)
  Asset:            undefined
Runtime:
  Name:             OpenJDK Runtime Environment
  Version:          17.0.6+10-LTS
  Vendor:           Amazon.com Inc.

2023-02-04 09:03:46.187  INFO 14368 --- [lag-collector-1] CollectorEvent.COLLECTOR_RUN_BEGIN       : collector-1
2023-02-04 09:03:46,187 INFO [collector-1] C.COLLECTOR_RUN_BEGIN [SLF4JUtil.java:39] collector-1
2023-02-04 09:03:46.196  INFO 14368 --- [lag-collector-1] CollectorEvent.COLLECTOR_RUN_END         : collector-1
2023-02-04 09:03:46,196 INFO [collector-1] C.COLLECTOR_RUN_END [SLF4JUtil.java:39] collector-1
2023-02-04 09:03:46.204 ERROR 14368 --- [lag-collector-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.example.acquire.websitecrawler.service.WebCrawlerService.startWebCrawler() throws org.apache.commons.cli.MissingArgumentException

java.lang.NoSuchMethodError: 'org.openqa.selenium.chrome.ChromeOptions org.openqa.selenium.chrome.ChromeOptions.setHeadless(boolean)'
	at com.norconex.collector.http.fetch.impl.webdriver.Browser$1.driverSupplier(Browser.java:61)
	at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHolder.<init>(WebDriverHolder.java:52)
	at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher.fetcherStartup(WebDriverHttpFetcher.java:233)
	at com.norconex.collector.http.fetch.AbstractHttpFetcher.accept(AbstractHttpFetcher.java:142)
	at com.norconex.collector.http.fetch.AbstractHttpFetcher.accept(AbstractHttpFetcher.java:82)
	at com.norconex.commons.lang.event.EventManager.doFire(EventManager.java:144)
	at com.norconex.commons.lang.event.EventManager.fire(EventManager.java:125)
	at com.norconex.commons.lang.event.EventManager.fire(EventManager.java:119)
	at com.norconex.collector.core.Collector.start(Collector.java:185)
	at com.example.acquire.websitecrawler.service.WebCrawlerService.startWebCrawler(WebCrawlerService.java:49)
	at com.example.acquire.websitecrawler.service.WebCrawlerService$$FastClassBySpringCGLIB$$73b1a8f4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-02-04 09:03:46,204 ERROR [collector-1] o.s.a.i.SimpleAsyncUncaughtExceptionHandler [SimpleAsyncUncaughtExceptionHandler.java:39] Unexpected exception occurred invoking async method: public void com.example.acquire.websitecrawler.service.WebCrawlerService.startWebCrawler() throws org.apache.commons.cli.MissingArgumentException
java.lang.NoSuchMethodError: 'org.openqa.selenium.chrome.ChromeOptions org.openqa.selenium.chrome.ChromeOptions.setHeadless(boolean)'
	at com.norconex.collector.http.fetch.impl.webdriver.Browser$1.driverSupplier(Browser.java:61)
	at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHolder.<init>(WebDriverHolder.java:52)
	at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher.fetcherStartup(WebDriverHttpFetcher.java:233)
	at com.norconex.collector.http.fetch.AbstractHttpFetcher.accept(AbstractHttpFetcher.java:142)
	at com.norconex.collector.http.fetch.AbstractHttpFetcher.accept(AbstractHttpFetcher.java:82)
	at com.norconex.commons.lang.event.EventManager.doFire(EventManager.java:144)
	at com.norconex.commons.lang.event.EventManager.fire(EventManager.java:125)
	at com.norconex.commons.lang.event.EventManager.fire(EventManager.java:119)
	at com.norconex.collector.core.Collector.start(Collector.java:185)
	at com.example.acquire.websitecrawler.service.WebCrawlerService.startWebCrawler(WebCrawlerService.java:49)
	at com.example.acquire.websitecrawler.service.WebCrawlerService$$FastClassBySpringCGLIB$$73b1a8f4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
````

Thank you!

**Comment by essiembre** [comment]
@lg255 Thanks for sharing your appreciation. 

A few more questions to help isolate the issue you're facing:

* Which selenium version is reported when you resolve the maven dependencies in your project?  Can you share what you get from running `mvn dependency:tree`? The latest release version of this project ships with selenium 3.141.59.
* Do you get this error when you run the crawler on its own (as opposed to within spring boot)?
* Do you get this error when you run the crawler with Java 8?  The targeted version is Java 8 (and will be until the next major release).

**Comment by lg255** [comment]
Hello,

thank you very much for pointing me in the right direction. I was able to find another conflicting version of Selenium brought into the application from another dependency. I could resolve the conflict and it is working now.

Could I just ask one other thing? After the crawler is finished, it seems that the Chrome and chromedriver processes are not being stopped correctly. Is there an option to tell the crawler to do so?

Anyway, thanks again for your help and sorry for any inconvenience!

Best regards!

**Comment by essiembre** [comment]
I am not sure why it does not shut down for you, as the WebDriverHttpFetcher does it for you at the end of every thread it creates.  Maybe you can research which process still has a hold of your browser when this happens and report it.   In the worst case, you can look at adding an event listener to your crawler, which will kill faulty processes it finds when the crawler stops.
