### ISSUE TITLE
Crawler fails after few seconds: Cannot create status file

### ISSUE THREAD

**Issue by feuerdav** [Norconex/collector-http#94]
We start a Http-crawler via cron and occasionally it stops with the following exception after few seconds:
FATAL [AbstractCrawler$ProcessURLsRunnable] MyCrawler: An error occured that could compromise the stability of the crawler. Stopping excution to avoid further issues...
com.norconex.jef4.JEFException: Cannot persist status update for job: MyCrawler
        at com.norconex.jef4.suite.JobSuite$2.statusUpdated(JobSuite.java:341)
        at com.norconex.jef4.status.JobStatusUpdater$1.mapChanged(JobStatusUpdater.java:33)
        at com.norconex.commons.lang.map.MapChangeSupport.fireMapChange(MapChangeSupport.java:103)
        at com.norconex.commons.lang.map.ObservableMap.put(ObservableMap.java:102)
        at com.norconex.commons.lang.map.Properties.setString(Properties.java:572)
        at com.norconex.commons.lang.map.Properties.setInt(Properties.java:650)
        at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:376)
        at com.norconex.collector.core.crawler.AbstractCrawler$ProcessURLsRunnable.run(AbstractCrawler.java:615)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot create status file: /opt/MyCrawler/output/progress/latest/status/MyCrawler__MyCrawler.job
        at com.norconex.jef4.status.FileJobStatusStore.write(FileJobStatusStore.java:117)
        at com.norconex.jef4.suite.JobSuite$2.statusUpdated(JobSuite.java:339)
        ... 10 more

The mentioned job file will have a prop.processedCount of less than 10 AND an endTime-Parameter (so the JEF could write to it after the exception).
We configured <numThreads>6</numThreads> and have a handful of starturls.

Is there any fix or workaround for this?

Udate: We're using version norconex-collector-http-2.0.1

Thanks a lot!

**Comment by essiembre** [comment]
What the error suggests, is it could not write a file to that location for some reason: /opt/MyCrawler/output/progress/latest/status/MyCrawler__MyCrawler.job

Can it be permission issues?  Does the user running the cronjob have permissions on the directories/files?

There has been quite a few fixes since.  2.1.0 is out, and there are snapshot version of 2.2.0 available also.  I recommend you test with a more recent version and confirm if this happens again.

**Comment by feuerdav** [comment]
We updated to version 2.1.0 and had no issues for quite many crawler runs - seems the problem is solved.
Thank you!
